# Generated by Django 5.2 on 2025-04-28 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2019, 3, 27, 0, 0)),
            preserve_default=False,
        ),
    ]
