# Generated by Django 5.2 on 2025-04-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='text',
        ),
    ]
